//ecosystem.config.js
module.exports = {
  apps: [
    {
      name: 'grinbit.cms',
      interpreter: 'node',
      script: './server.js',
      instances: 0,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
        NODE_HTTP_HOST: '',
        NODE_HTTP_PORT: 8000,
        NODE_HTTPS_PORT: 8443,

        DB_HOST: '',
        DB_USER: '',
        DB_PASSWORD: '',
        DB_DATABASE: '',

        CMS_DB_HOST: '',
        CMS_DB_USER: '',
        CMS_DB_PASSWORD: '',
        CMS_DB_DATABASE: '',
        JWT_SECRET_KEY: '',

        GOOGLE_CLIENT_ID: '',
        GOOGLE_CLIENT_SECRET: '',
        NAVER_CLIENT_ID: '',
        NAVER_CLIENT_SECRET: '',
        KAKAO_CLIENT_ID: '',
        KAKAO_CLIENT_SECRET: '',
        APPLE_CLIENT_ID: '',
        APPLE_TEAM_ID: '',
        APPLE_KEY_ID: '',

        WALLET_ADDRESS: '',
        WALLET_KIP7_OLD: '',
        WALLET_KIP7_NEW: '',
        WALLET_FEE_ADDRESS: '',
        WALLET_FEE_PASSWORD: '',
        KEYSTOREPATH: '',
        BURN_STORAGE: '',
        SWAP_ADDRESS: '',
        SWAP_PASSWORD: '',
        STAKING_ADDRESS: '',
        STAKING_PASSWORD: '',

        SMS_KEY: '',
        SEND_EMAIL: '',
      },
      env_staging: {
        NODE_ENV: 'production',
        NODE_HTTP_HOST: '',
        NODE_HTTP_PORT: 8000,
        NODE_HTTPS_PORT: 8443,

        DB_HOST: '',
        DB_USER: '',
        DB_PASSWORD: '',
        DB_DATABASE: '',

        CMS_DB_HOST: '',
        CMS_DB_USER: '',
        CMS_DB_PASSWORD: '',
        CMS_DB_DATABASE: '',
        JWT_SECRET_KEY: '',

        GOOGLE_CLIENT_ID: '',
        GOOGLE_CLIENT_SECRET: '',
        NAVER_CLIENT_ID: '',
        NAVER_CLIENT_SECRET: '',
        KAKAO_CLIENT_ID: '',
        KAKAO_CLIENT_SECRET: '',
        APPLE_CLIENT_ID: '',
        APPLE_TEAM_ID: '',
        APPLE_KEY_ID: '',

        WALLET_ADDRESS: '',
        WALLET_KIP7_OLD: '',
        WALLET_KIP7_NEW: '',
        WALLET_FEE_ADDRESS: '',
        WALLET_FEE_PASSWORD: '',
        KEYSTOREPATH: '',
        BURN_STORAGE: '',
        SWAP_ADDRESS: '',
        SWAP_PASSWORD: '',
        STAKING_ADDRESS: '',
        STAKING_PASSWORD: '',
        SMS_KEY: '',
        SEND_EMAIL: '',
      },
      watch: true,
      ignore_watch: ['logs', 'node_modules'],
      merge_logs: true,
      out_file: './logs/out.log',
      error_file: './logs/error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
    },
  ],
  deploy: {
    production: {
      user: 'ofu',
      host: [{ host: '36.38.26.187', port: '243' }],
      key: '~/.ssh/grinbit.cms.key',
      ssh_options: 'StrictHostKeyChecking=no',
      repo: 'git@github.com:grinbit-korea/grinbit.cms.git',
      ref: 'origin/master',
      'post-setup': 'yarn ; pm2 start ecosystem.config.js --env production; pm2 save',
      'post-deploy': 'yarn ; pm2 reload ecosystem.config.js --env production',
      path: '/home/ofu/grinbit.cms',
    },
    staging: {
      user: 'ofu',
      host: [{ host: '36.38.26.186', port: '243' }],
      key: '~/.ssh/grinbit.cms.key',
      ssh_options: 'StrictHostKeyChecking=no',
      repo: 'git@github.com:grinbit-korea/grinbit.cms.git',
      ref: 'origin/develop',
      'post-setup': 'yarn ; pm2 start ecosystem.config.js --env staging; pm2 save',
      'post-deploy': 'yarn ; pm2 reload ecosystem.config.js --env staging',
      path: '/home/ofu/grinbit.cms',
    },
  },
};
